// emojiArt — render an emoji as its high-res Microsoft Fluent 3D asset when we
// have one bundled (public/card-art/, generated by scripts/fetch-card-art.mjs),
// otherwise fall back to the platform raster glyph. The Fluent PNGs stay crisp
// at any card size; raw emoji glyphs blur when scaled up to flashcard size.
import { CARD_ART } from '../data/cardArtManifest.js';

// true when we have a bundled Fluent 3D asset for this emoji — lets callers
// prefer it over a hand-drawn <Illu> while keeping the drawing as a fallback.
export const hasFluent = (char) => !!(char && CARD_ART[char]);

export const emojiArt = (char, size) => {
  const src = CARD_ART[char];
  if (src) {
    return (
      <img
        src={src}
        alt=""
        draggable={false}
        width={size}
        height={size}
        style={{ width: size, height: size, objectFit: 'contain', display: 'inline-block' }}
      />
    );
  }
  return <span style={{ fontSize: size, lineHeight: 1, display: 'inline-block' }}>{char}</span>;
};
